# Generated by Django 6.0.6 on 2026-06-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dangerous_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.TextField()),
                ('url_video', models.TextField()),
                ('event_status', models.CharField()),
                ('width', models.FloatField()),
                ('longitude', models.FloatField()),
                ('priority', models.IntegerField()),
                ('promt', models.TextField()),
                ('conf', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dangerous_event', to='accidents.category')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('stream_url', models.TextField()),
                ('width', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cur_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Camera', to='accidents.dangerous_event')),
            ],
        ),
    ]
