# Generated by Django 6.0.6 on 2026-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_alter_camera_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangerous_event',
            old_name='promt',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='dangerous_event',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
