# Generated by Django 6.0.6 on 2026-07-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_rename_promt_dangerous_event_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cur_event_id',
        ),
        migrations.RemoveField(
            model_name='dangerous_event',
            name='event_type_id',
        ),
    ]
