# Generated by Django 6.0.6 on 2026-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0004_remove_camera_cur_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangerous_event',
            old_name='width',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='dangerous_event',
            name='categorys',
            field=models.ManyToManyField(related_name='dangerous_events', to='accidents.category'),
        ),
    ]
