# Generated by Django 6.0.6 on 2026-07-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0005_rename_width_dangerous_event_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Explosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('conf', models.FloatField()),
                ('detected_objects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='width',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_owner',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='coordinates',
            field=models.CharField(default=5.324, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.TextField()),
                ('priority', models.IntegerField()),
                ('event_status', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('conf', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('event_types', models.ManyToManyField(related_name='events_types', to='accidents.category')),
                ('frames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_frames', to='accidents.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Dangerous_event',
        ),
    ]
