# Generated by Django 6.0.6 on 2026-07-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0006_collapse_explosion_fires_frame_journal_transport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_types',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frames',
        ),
        migrations.DeleteModel(
            name='Collapse',
        ),
        migrations.DeleteModel(
            name='Explosion',
        ),
        migrations.DeleteModel(
            name='Fires',
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
