# Generated by Django 6.0.6 on 2026-07-22 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_owner', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('stream_url', models.URLField()),
                ('coordinates', models.CharField(max_length=200)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('conf', models.FloatField()),
                ('detected_objects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_types', models.CharField(choices=[('accident', 'Авария'), ('collapse', 'Обрушение'), ('explosion', 'Взрыв'), ('fire', 'Пожар')])),
                ('video_url', models.URLField()),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('event_status', models.CharField(default='New', verbose_name=[('New', 'Новый'), ('In_progress', 'В прогрессе'), ('Resolved', 'Закрыт'), ('False_posirive', 'Ложное срабатывание')])),
                ('desc', models.TextField()),
                ('conf', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_frames', to='events.frame')),
            ],
        ),
    ]
