# Generated by Django 6.0.6 on 2026-07-22 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.CharField(choices=[('accident', 'Авария'), ('collapse', 'Обрушение'), ('explosion', 'Взрыв'), ('fire', 'Пожар')], verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
