# Generated by Django 6.0.6 on 2026-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_types_alter_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.CharField(choices=[('accident', 'Авария'), ('collapse', 'Обрушение'), ('explosion', 'Взрыв'), ('fire', 'Пожар')], max_length=9, verbose_name='type'),
        ),
    ]
