# Generated by Django 6.0.6 on 2026-07-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_types',
            new_name='event_type',
        ),
    ]
