# Generated by Django 6.0.6 on 2026-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_types_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('New', 'Новый'), ('In_progress', 'В прогрессе'), ('Resolved', 'Закрыт'), ('False_posirive', 'Ложное срабатывание')], default='New', verbose_name='status'),
        ),
    ]
