# Generated by Django 6.0.6 on 2026-07-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], verbose_name='priority'),
        ),
    ]
