# Generated by Django 6.0.6 on 2026-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', verbose_name='priority'),
        ),
    ]
